framework:
    cache:
        default_memcached_provider: 'memcached://%env(MEMCACHED_HOST)%:%env(MEMCACHED_PORT)%'
        pools:
            http.cache.cbr_request:
                adapter: cache.adapter.array
                public: false
                default_lifetime: 86400
