httplug:
    plugins:
        retry:
            retry: 1

    discovery:
        client: 'auto'

    clients:
        app:
            http_methods_client: true
            plugins:
                - 'httplug.plugin.content_length'
                - 'httplug.plugin.redirect'

        cbr_api:
            factory: 'httplug.factory.guzzle6'
            flexible_client: true
            plugins:
                - 'httplug.plugin.logger'
                - 'httplug.plugin.error'
                - 'httplug.plugin.content_length'
                - 'httplug.plugin.redirect'
            config:
                CURLOPT_TIMEOUT: 2